### ISSUE TITLE
2주치 목표

### ISSUE THREAD

**Issue by tttghost** [tttghost/wheelmaker#54]
싱글톤 제거(singleton.cs)
---
- [x] #55

기존기능 역설계
---
- 기존에 개발했던 기능들에 대해 역설계 해 기능단위로 구분, 구분한 기능들에 대해 인터페이스화 한다.
1. **플레이어**
돈을 획득한다 GetMoney(int value)
캐릭터를 변경한다 ChangeCharacter(int index)
레벨업을 한다 LevelUp(int value) 
...
2. **UI**
창을 띄운다 Show()
창을 닫는다 Hide()
컨텐츠를 넣는다 UpdateContent(object Object)
...

---

캐싱을 하는 Util.Search도 제거, 인스펙터에 연결
---
- 기존코드 의존적인 부분 제거하기 위함

프로그래머의 길, 멘토에게 묻다. 완독
---
- 완독 후 느낀점에 대해 설명드린다.

**Comment by jongfeel** [comment]
저는 singleton 제거 목표만 가지고 해봐도 좋을 것 같다는 의견입니다.
물론 완료가 목표가 아닙니다. 진행형으로 2주를 잡아도 되요.
이것도 완료 하려면 오래 걸릴 수도 있습니다.

singleton을 사용하는 곳에서 singleton을 제거했을 때 보완해줘야 하는 코드를 설계하고 만드는 것도 일일 수 있습니다.

**Comment by tttghost** [comment]
네 싱글톤 제거 목표 하나만 가지고 해보겠습니다.
일단 시작을시작을

**Comment by tttghost** [comment]
목표치 대비 시작도
작성해주신 코드 마지막 날 분석하고 있는 중입니다..

**Comment by tttghost** [comment]
2주치 목표 수행시간 : 3시간.

느낀점 : 가이드 코드작업을 해 주셨는데도 해당 코드를 보며 생각할 부분이 참 많았습니다.
사실 봐서 이해되는 부분이 많았고 골드를 나누는 부분이나 ILevel설계 부분과 그 인자로 Behaviours를 넘기는 것은
잠깐 봐서 익숙해 질 부분이 아닌것 같다고 생각이 들었습니다.

이렇게 가이드코드까지 작성해 주셨는데도 좀더 열심히 하지않은 제 자신을 돌아보며.. 코멘트 남깁니다..

**Comment by jongfeel** [comment]
> 저는 singleton 제거 목표만 가지고 해봐도 좋을 것 같다는 의견입니다. 물론 완료가 목표가 아닙니다. 진행형으로 2주를 잡아도 되요. 이것도 완료 하려면 오래 걸릴 수도 있습니다.
> 
> singleton을 사용하는 곳에서 singleton을 제거했을 때 보완해줘야 하는 코드를 설계하고 만드는 것도 일일 수 있습니다.

제가 여기서 진행형이라고 얘기한 부분을 꼭 기억해 주셨으면 합니다.
어제 멘토링 때 많이 설명 드린 부분이고
한국식 개념의 "성장" 보다는
외국(미국)식 개념의 "전진(progress)"라고 이해하셔야 합니다.

따라서 전진(progress)을 위해 진행중(in progress)이어야 함을 잊지 말아 주세요.

**Comment by tttghost** [comment]
오래된 이슈로 close처리 하겠습니다.
