### ISSUE TITLE
Remove singleton - SoundManager

### ISSUE THREAD

**Issue by tttghost** [tttghost/wheelmaker#64]
### SoundManager

사운드 라는것이 **객체** 이다.
객체에 대한 동작을 정의한다.

아이디어
---
사운드는 재생과 멈출수 있고 보륨조절이 가능하다.
조절한 볼륨의 크기도 알수 있어야 할 것 같다.
오디오클립도 바꿀수 있고 1회성재생? 도 필요할 것 같다.
그리고 사운드를 루프시킬 지 여부도 정한다.

구체화
---
재생한다. 
멈춘다.
볼륨을 조절한다.
현재 볼륨을 가져온다. 
오디오클립을 바꾼다. 
1회성 재생을 한다.
사운드 반복재생/단일재생을 한다.

Interface 설계
---
```c#
interface ISound
{
    void Play();
    void Stop();
    void SetVolume(float volume);
    float GetVolume();
    void SetAudioClip(AudioClip audioClip);
    void PlayEffect();
    void SetLoop(float isLoop);
}
```

적다보니 궁금점
---
- 일반 재생과 1회성 재생을 나누는 것??
- ISound 이게 객체이다. 어떤 사운드를 조절할 지가 아니라 인터페이스 자체가 객체이다? 
- 이 기능들이 하나의 인터페이스에 통합되는것일까요..?
- 이 단계까지 하는것인지 어떻게 이야기 해야할지 모르겠습니다.

Progress 1/100 ...

**Comment by tttghost** [comment]
프로그래스형식으로 미리미리해야하는데 어렵습니다아..

**Comment by jongfeel** [comment]
ISound interface에 operation이 7개는 너무 많습니다.
분리가 필요합니다.

1. volume

set, get이 노출 되어 있다는 건 volume의 데이터 값에 대한 접근입니다.
따라서 별도의 인터페이스로 하는 게 좋을 수 있을 것 같습니다.

2. AudioClip

AudioClip도 전달해 줘야 하는 거면
전달이 되지 않을 때 다른 operation의 동작이 안될 가능성이 높다고 봅니다.
AudioClip이라는 데이터를 주는 역할만 하는 거면
인터페이스가 아니라 클래스 내에 있어도 될 것 같습니다.
그러면 없어도 되겠죠

3. PlayEffect

Effect라는 단어와 1회 플레이를 한다는 단어 뜻이 맞지 않습니다.
그리고 유니티에도 PlayOneShot() 이라는 메소드가 있으므로 같은 뜻으로 사용해봐도 좋을 것 같습니다.

4. SetLoop()

설정은 되는데 loop를 안하고 싶으면 어떻게 할까요?
loop가 되는 audio와 안해도 되는 auidio를 나누는 게 좋을 것 같습니다.

그래서 제가 제안하는 interface 설계는 다음과 같습니다.

```c#
interface IVolumeControl
{
    float Value { get; set; }
}
```

```c#
interface IAudioControl
{
    void Play();
    void Stop();
}
```

```c#
interface IOneShotAudioControl
{
    void Play();
    void Stop();
}
```

```c#
interface ILoopAudioControl : IAudioControl
{
    bool IsLoop { get; set; }
}
```

이제 여기서 궁금증에 대한 논의를 해보면

### 일반 재생과 1회성 재생을 나누는 것??

나눠 봤습니다. 나누면 더 명확해질 것 같습니다.

### ISound 이게 객체이다. 어떤 사운드를 조절할 지가 아니라 인터페이스 자체가 객체이다?

네, 어떤 사운드인지는 중요하지 않습니다. Play 해라, Stop 해라. 이 관점이 더 중요합니다.

### 이 기능들이 하나의 인터페이스에 통합되는것일까요..?

하나의 기능에 다 구현하기에는 너무 많으므로 나눠 본 것입니다.
인터페이스의 특성상 다중 상속 구현이 가능하므로
필요하다면 인터페이스를 전부 상속받아서 구현해도 됩니다.

### 이 단계까지 하는것인지 어떻게 이야기 해야할지 모르겠습니다.

저의 설계 제안과 추가 설명을 보고 더 의견을 나눠보면 됩니다.

**Comment by tttghost** [comment]
보면 이해가 딱 되는데
제가 하기에는 아직 탁 하고 감이 오질 않습니다.
당연한 거 이겠지만 쉽지 않네요...!

기존코드인
```c#
public enum eAudioMixerType
{
    Master,
    Music,
    SoundEffects,
    Dialogue,
    Ambience,
    Interface,
}
```
위 코드를 보시면 AudioMixer를 사용하며 게임을 기준으로 하면 음악이 있을것이고 
환경음이 있을 것이고... 하는 것들을 미리 정의하고 사용하려고 했었습니다.
그런데 이 부분 자체도 오버엔지니어링 이라는 말을 해주신 부분이 와 닿았습니다.

위의 인터페이스로 정의된 것들을 어떻게 클래스에 녹여내야 할 지도 궁금한 부분입니다.

**Comment by tttghost** [comment]
그리고 의견을 더 나누는 방식이
제가 어떤 질문을 어떻게 해야할지 질문의 방식을 잘 못하는 것 같습니다...

**Comment by jongfeel** [comment]
> 보면 이해가 딱 되는데 제가 하기에는 아직 탁 하고 감이 오질 않습니다. 당연한 거 이겠지만 쉽지 않네요...! 기존코드인
> 
> ```cs
> public enum eAudioMixerType
> {
>     Master,
>     Music,
>     SoundEffects,
>     Dialogue,
>     Ambience,
>     Interface,
> }
> ```
> 
> 위 코드를 보시면 AudioMixer를 사용하며 게임을 기준으로 하면 음악이 있을것이고 환경음이 있을 것이고... 하는 것들을 미리 정의하고 사용하려고 했었습니다. 그런데 이 부분 자체도 오버엔지니어링 이라는 말을 해주신 부분이 와 닿았습니다.
> 
> 위의 인터페이스로 정의된 것들을 어떻게 클래스에 녹여내야 할 지도 궁금한 부분입니다.

적어주신 코드는 enum 값인데 이게 인터페이스의 역할을 하는 거라고 생각했다면
각 항목별로 행위에 해당하는 메소드 정의가 있는 진짜 인터페이스 부터 하나를 만드는 것 부터 해보는게 좋습니다.

또 인터페이스로 정의된 건 당연히 클래스에서 구현해야 합니다.
그건 구현해 보면서 판단해 봐도 됩니다.

**Comment by jongfeel** [comment]
> 그리고 의견을 더 나누는 방식이 제가 어떤 질문을 어떻게 해야할지 질문의 방식을 잘 못하는 것 같습니다...
> 
> * 좀 더 기능을 붙이는 쪽으로 질문을 해야할지?
> * 아니면 제안해 주신 방식으로 개발을 진행한다고 해보는 방식일지?
> * 제안주신 방식이 좋다고 이야기 해야할지?
> 
> 이런 고민이 듭니다!!

질문 순서를 1번, 2번, 3번이라고 해보면
고민의 순서를 1번 -> 3번 -> 2번의 순서로 해보시면 좋겠습니다.

우선 1번을 먼저 고려해 보는게 좋습니다. 기능이 빠진 건 없는지, 더 추가되거나 필요 없다고 생각하는게 있는지에 대한 의견을 주시면 됩니다.
그러면 그걸 토대로 제가 확인해 보고 더 수정하거나 그대로 진행할지를 논의하는 거죠.

그 다음 1번의 고민이 더 이상 없거나 해결 됐다면 3번으로 결정하면 좋습니다.
2번의 경우는 3번이 결정 된 이후에 하면 됩니다.

순서를 다시 정리해 보면

- 설계 부분을 논의 한다.
- 리뷰를 통해 협의점을 찾는다.
- 서로 협의가 이루어 졌다면 구현을 해 본다.

입니다.

**Comment by tttghost** [comment]
interface IAudioControl
{
    void Play();
    void Stop();
}

에 대한 설계 저도 동의 합니다!
이 부분대로 구현 해볼까요?

**Comment by jongfeel** [comment]
네 바로 구현 해보시죠.

그리고 리팩터링이 상당히 많이 들어갈 수도 있는데
이 부분에 대한 고민이 있으면 같이 얘기해보면 좋을 수 있습니다.

**Comment by tttghost** [comment]
네 알겠습니다!
가위를 만들자...

________________________________
보낸 사람: Kim Jong Feel ***@***.***>
보낸 날짜: 2024년 12월 9일 월요일 오전 11:35
받는 사람: tttghost/wheelmaker ***@***.***>
참조: 김지수 ***@***.***>; Assign ***@***.***>
제목: Re: [tttghost/wheelmaker] Remove singleton - SoundManager (Issue #64)


네 바로 구현 해보시죠.

그리고 리팩터링이 상당히 많이 들어갈 수도 있는데
이 부분에 대한 고민이 있으면 같이 얘기해보면 좋을 수 있습니다.

**Comment by tttghost** [comment]
이 이슈는 기준이되는 Remove Singleton SoundManager 가 있기에 close처리 및 링크만 걸어두겠습니다.
