### ISSUE TITLE
시작하기 버튼 클릭 시 로그 출력

### ISSUE THREAD

**Issue by jongfeel** [tttghost/wheelmaker#8]
## Overview

시작하기 버튼이 현재 동작하고 있지 않음
gitflow 예시를 위해 버튼 클릭 후 로그 출력 스크립트 작성

## Design

시작하기 버튼인 btn_Start의 OnClick 이벤트에 대해 Component에 추가
추가할 스크립트는 Manager라는 이름으로 하고 panel_Main에 붙여 둠
시작이 됐다는 함수는 Manager.OnStart() 함수를 호출해서 "Start"라는 로그 출력

**Comment by tttghost** [comment]
그리고 기존 pullrequest했던 원격브랜치는 삭제했습니다.
맞을까요?
